name: Dockerfile Vulnerability Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@v1.9.0
        with:
          version: 'latest'

      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Test Dockerfile for vulnerabilities and output SARIF
        run: snyk container test --file=Dockerfile --sarif-file-output=snyk-report.sarif

      - name: Upload SARIF file to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-report.sarif
