name: Dockerfile Vulnerability Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Actualiza a la versi칩n m치s reciente

      - name: Install Node.js
        uses: actions/setup-node@v4  # Usa la versi칩n m치s reciente
        with:
          node-version: '20'  # Cambia a Node.js 20

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Test Dockerfile for vulnerabilities
        continue-on-error: true
        run: snyk container test --file=Dockerfile --json-file-output=snyk-result.json

      - name: Upload Snyk JSON results
        if: always()
        uses: actions/upload-artifact@v3  # Confirmado como compatible
        with:
          name: snyk-results
          path: snyk-result.json

      - name: Print vulnerabilities summary
        if: failure()
        run: |
          echo "Vulnerabilities were detected. Review the 'snyk-result.json' artifact."
          exit 0
